### ISSUE TITLE
[Bug] Occasional segmentation fault during map loads

### ISSUE THREAD

**Issue by Vagankovo** [Novum/vkQuake#415] opened 2022-01-06 12:57 UTC
## System info
OS - Arch Linux (rolling)
GPU - Radeon RX 5500M & AMD Renoir (integrated graphics)
Vulkan driver - RADV (part of Mesa)
CPU - Ryzen 7 4800H with Radeon Graphics

vkquake version - latest git commit

## Bug
The engine sometimes crashes with a segmentation fault during map loads.

## Reproduction
Consistent reproduction steps are currently unknown. However, I assume that it will happen with enough level loads, so one can load a level on a loop in an attempt to reproduce this.

**Comment by vsonnier** [comment] 2022-01-06 14:03
Hi @Vagankovo @Novum, I also encountered the crash at map load precisely since the lignmap water commit. 

For me this is reproducible with this map: https://www.quaddicted.com/reviews/symphony_v101.html

Tested with `master` compiled with VS2022 x64.

**Comment by Novum** [comment] 2022-01-07 04:29
Can't reproduce so far. Not even with AppVerifier.

**Comment by vsonnier** [comment] 2022-01-07 07:03
> Can't reproduce so far. Not even with AppVerifier.

Thanks @Novum for trying. It indeed looks random now with the same map:  crash/freeze 2 times in a row this morning, but can't reproduce afterwards even trying multiple times ? (using latest `master`). Some setting in `config.cfg` correcting itself ? Okay. I'll report here if I found a really reproducible situation.

**Comment by Novum** [comment] 2022-01-07 07:11
I really would need a crash dump to debug this better

**Comment by Vagankovo** [comment] 2022-01-07 09:35
Where does vkQuake put the crash dump?

**Comment by Novum** [comment] 2022-01-07 09:38
It doesn't. You would have to get that from a debugger.

Fixed in d567e63393725df22aa31952c43ebb57b180da9b - if not please reopen.

**Closed by Novum** 2022-01-07 09:38 UTC
