### ISSUE TITLE
Console messages not appearing correctly with remastered

### ISSUE THREAD

**Issue by spinningeyeballs** [Novum/vkQuake#408] opened 2021-12-03 16:31 UTC
Since updating to 1.12.1 (win64) the console messages when picking up ammo, etc are not displaying correctly. This is using the remasterd version pak files.  

![vkQuake 2021-12-03 12-18-07](https://user-images.githubusercontent.com/95480869/144636825-81a299b5-74b1-4bd0-ae20-1fe1199facc1.png)

**Comment by Novum** [comment] 2021-12-03 18:20
Undocumented extension, needs reverse engineering.

**Comment by sezero** [comment] 2021-12-03 18:55
I built git master for win64, put vquake.exe (and dlls) under rerelease directory, I can't reproduce the issue?

**Comment by Novum** [comment] 2021-12-03 19:06
I can def. reproduce it, I saw it yesterday in mg1 horde2

**Comment by sezero** [comment] 2021-12-03 19:21
Is this a new update to rerelease or something? I can't find any map named `horde*` under mg1 in my copy.

**Comment by sezero** [comment] 2021-12-03 19:26
Answering to my own question - an update/2 seems to be out. Ugh.
https://store.steampowered.com/news/app/2310/view/3102414008261877214

**Comment by andrei-drexler** [comment] 2021-12-03 20:29
Fixed in https://github.com/Novum/vkQuake/commit/b7e659fcbf0f53f6abc3c842cbe3642410dc1027.

**Closed by andrei-drexler** 2021-12-03 20:29 UTC
Labels: enhancement
