### ISSUE TITLE
Texture transparency doesn't work properly

### ISSUE THREAD

**Issue by Vagankovo** [Novum/vkQuake#473] opened 2022-05-28 06:00 UTC
## System specifications
OS - Arch Linux (rolling)
GPU - Radeon RX 5500M & AMD Renoir (integrated graphics)
Vulkan drivers - RADV (part of Mesa graphics libraries)
CPU - Ryzen 7 4800H with Radeon Graphics

vkquake version - latest git commit

## Bug
Texture transparency only works when viewing textures under certain angles, as shown in Alkaline's start map.
![Screenshot from 2022-05-28 08-57-37](https://user-images.githubusercontent.com/90520453/170812365-e84bab46-3768-4234-97e2-e08e1845285d.png)
![Screenshot from 2022-05-28 08-57-40](https://user-images.githubusercontent.com/90520453/170812366-12216095-1b6e-4c88-82b4-11f341fcf877.png)

## Reproduction
1. Load Alkaline's start map
2. See that the windows are opaque
3. Turn right until the windows become transparent.

**Comment by Novum** [comment] 2022-05-28 18:44
Can't reproduce this as of 812fd983dced967d1051ddc129336c1bd84981ce
Still happening?

**Comment by Vagankovo** [comment] 2022-05-28 19:27
Unable to check, as the build fails.
```
cc -DNDEBUG -c -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wall -Wno-trigraphs -Wno-unused-function -Werror -std=gnu11  -O3 -fweb -frename-registers -DDO_USERDIRS=1 -DUSE_CODEC_WAVE -DUSE_CODEC_FLAC -DUSE_CODEC_OPUS -I/usr/include/opus  -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DUSE_CODEC_MIKMOD -DUSE_CODEC_UMX -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o tasks.o tasks.c
tasks.c: In function ‘Tasks_Init’:
tasks.c:297:55: error: writing 16 bytes into a region of size 0 [-Werror=stringop-overflow=]
  297 |                 steal_worker_indices[i + num_workers] = i;
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
tasks.c:87:24: note: at offset 64 into destination object ‘steal_worker_indices’ of size 64
   87 | static uint8_t         steal_worker_indices[MAX_WORKERS * 2];
      |                        ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:185: tasks.o] Error 1
make: Leaving directory '/home/ivan/.cache/paru/clone/vkquake-git/src/vkquake/Quake'
```

**Comment by Novum** [comment] 2022-05-28 20:46
What compiler is that? Can't reproduce that either.

**Comment by sezero** [comment] 2022-05-28 20:49
That looks like gcc, possibly version 8 or later. (You should update Makefile.w32 and Makefile.w64, btw.)

**Comment by sezero** [comment] 2022-05-28 20:50
> That warning is bullshit.

My experience, 70% of the time yes bullshit, but _sometimes_ it's right.

**Comment by Novum** [comment] 2022-05-28 20:50
But this is nonsense.

**Comment by sezero** [comment] 2022-05-28 20:52
As I said, 70% of the time it's nonsense :)

**Comment by Novum** [comment] 2022-05-28 20:53
So how do we suppress this?

**Comment by sezero** [comment] 2022-05-28 20:54
Not specific to mingw, can (should) happen with any gcc with the right version.

**Comment by Novum** [comment] 2022-05-28 20:54
@Vagankovo where are those compiler flags coming from? I'm certainly not setting `-fexceptions`? This looks super unsupported.

**Comment by sezero** [comment] 2022-05-28 20:56
> So how do we suppress this?

Let me work a bit and get back to you.

**Comment by Vagankovo** [comment] 2022-05-28 21:03
@Novum Not sure. I'm using the AUR pkgbuild script, the culprit that I see is `%(maybe_debug)`: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vkquake-git

**Comment by Novum** [comment] 2022-05-28 21:06
Sorry, but this is unsupported. I have no idea what an "AUR pkgbuild script" is. Use the provided makefiles please.

**Comment by Vagankovo** [comment] 2022-05-28 21:13
The "supported" makefile:
```
cc -DNDEBUG -c -Wall -Wno-trigraphs -Wno-unused-function -Werror -std=gnu11  -O3 -fweb -frename-registers -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -DLINUX -I/usr/include/SDL2 -D_REENTRANT -o tasks.o tasks.c
tasks.c: In function ‘Tasks_Init’:
tasks.c:297:55: error: writing 16 bytes into a region of size 0 [-Werror=stringop-overflow=]
  297 |                 steal_worker_indices[i + num_workers] = i;
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
tasks.c:87:24: note: at offset 64 into destination object ‘steal_worker_indices’ of size 64
   87 | static uint8_t         steal_worker_indices[MAX_WORKERS * 2];
      |                        ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:185: tasks.o] Error 1
```
However, when I pass the `DEBUG=1` option, it manages to compile.
The bug still persists.
![Screenshot from 2022-05-29 00-12-22](https://user-images.githubusercontent.com/90520453/170843005-10d5a844-a86f-430c-b997-c4fadf5eb07f.png)

**Comment by sezero** [comment] 2022-05-28 21:18
The newest gcc versions I have access to at the moment are v8 and v9,
and I can't reproduce the warning with them. Two ideas, _neither_ are tested:

- change `num_workers` to an uint8_t and the   loop counter `i` (at line 297)
  as well: dose it help? (shooting in the dark here..)

- if it doesn't, then something like the following should silence it:
```diff
diff --git a/Quake/tasks.c b/Quake/tasks.c
index d10f1a9..1768f4a 100644
--- a/Quake/tasks.c
+++ b/Quake/tasks.c
@@ -290,12 +290,19 @@ void Tasks_Init (void)
 
 	num_workers = CLAMP (1, SDL_GetCPUCount (), MAX_WORKERS);
 
+#if defined(__GNUC__) && (__GNUC__ >= 8)
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wstringop-overflow"
+#endif
 	// Fill lookup table to avoid modulo in Task_ExecuteIndexed
 	for (int i = 0; i < num_workers; ++i)
 	{
 		steal_worker_indices[i] = i;
 		steal_worker_indices[i + num_workers] = i;
 	}
+#if defined(__GNUC__) && (__GNUC__ >= 8)
+#pragma GCC diagnostic pop
+#endif
 
 	indexed_task_counters = calloc (sizeof (task_counter_t) * num_workers * MAX_PENDING_TASKS, 1);
 	worker_threads = (SDL_Thread **)malloc (sizeof (SDL_Thread *) * num_workers);
```

**Comment by Novum** [comment] 2022-05-28 21:37
I'm on GCC 11.2 btw. so this isn't some new thing.

**Comment by Novum** [comment] 2022-05-29 06:03
@[Vagankovo](https://github.com/Vagankovo) does it go away with r_tasks set to 0?

**Comment by Vagankovo** [comment] 2022-05-29 07:20
No

**Comment by Novum** [comment] 2022-05-29 09:08
This might actually be a driver issue then, it's clean with validation layers.

**Comment by j4reporting** [comment] 2022-05-31 20:40
same issue on Windows  10 with current git version on a NVidia GTX 2060  and **alkaline 1.1** 
vkQuake  1.13.1  + alkaline 1.1:  no issues
vkQuake git   and older alkaline 1.0 version:  no issues

**Comment by temx** [comment] 2022-05-31 23:43
Should be fixed by https://github.com/Novum/vkQuake/commit/de692b2df1bd909502a65ce47d89a0d92062eb83
Were you running with `r_novis 1`?

**Comment by j4reporting** [comment] 2022-06-01 00:07
oh dear.  yes,  the alk1.1 config  had still `r_novis 1` enabled.   Windows are transparent with  `r_novis 0`

**Closed** 2022-06-01 02:05 UTC
Labels: bug
