### ISSUE TITLE
Messages are no longer printed with new remaster update

### ISSUE THREAD

**Issue by neclepsio** [Novum/vkQuake#379] opened 2021-10-09 20:47 UTC
No message is printed: difficulty selection, episode selection, secrets... Localization messages are correctly loaded. The sound is played.

**Comment by neclepsio** [comment] 2021-10-09 20:49
Maybe duplicate of #378, since `centerprint` code has been changed?

**Comment by neclepsio** [comment] 2021-10-10 15:15
Applying the patch in https://github.com/Novum/vkQuake/issues/378#issuecomment-939152721 is not enough to solve the problem. I don't know if it's relevant, but https://www.gamepretty.com/quake-kex-enhanced-cvar-command-list/ mentions `scr_displayCenterMessages` as new cvar. Also: vkQuake prints a message on console complaining for missing cvar `scr_usekfont`.

**Comment by sezero** [comment] 2021-10-16 21:39
I just had time to actually test this using vkquake and yes I reproduced the issue.
quakespasm works fine, don't yet know what is wrong with vkquake.  @andrei-drexler,
@Novum?

**Comment by andrei-drexler** [comment] 2021-10-17 08:55
The issue is that vkQuake already has some extension builtins with the same id's as the ones added in the new update, e.g.
https://github.com/Novum/vkQuake/blob/4611d7390680f8e7199c2e85f0324b4629498807/Quake/pr_ext.c#L4281-L4283

(corresponding to `DP_QC_TRACEBOX`, `DP_QC_RANDOMVEC`, `DP_QC_GETLIGHT`), so `PF_tracebox` will be called instead of the `PF_centerprint` added in https://github.com/Novum/vkQuake/commit/fb9a13478efb71b5fdff344ca29f949ea686eb20. An easy fix would be to remove these extensions, but `tracebox` and `randomvec` might actually be useful. Another option would be to patch the rerelease builtins to point to their old indices, something like
```diff
diff --git a/Quake/pr_edict.c b/Quake/pr_edict.c
index 6c9a496..56dcf66 100644
--- a/Quake/pr_edict.c
+++ b/Quake/pr_edict.c
@@ -1183,6 +1183,28 @@ static void PR_MergeEngineFieldDefs (void)
 	}
 }
 
+/*
+===============
+PR_PatchRereleaseBuiltins
+
+Quake 2021 release update 1 adds bprint/sprint/centerprint builtins with new id's
+(see https://steamcommunity.com/games/2310/announcements/detail/2943653788150871156)
+This function patches them back to use the old indices
+===============
+*/
+static void PR_PatchRereleaseBuiltins (void)
+{
+	dfunction_t *f;
+	if (qcvm != &sv.qcvm)
+		return;
+	if ((f = ED_FindFunction ("centerprint")) != NULL && f->first_statement == -90)
+		f->first_statement = -73;
+	if ((f = ED_FindFunction ("bprint")) != NULL && f->first_statement == -91)
+		f->first_statement = -23;
+	if ((f = ED_FindFunction ("sprint")) != NULL && f->first_statement == -92)
+		f->first_statement = -24;
+}
+
 /*
 ===============
 PR_LoadProgs
@@ -1330,6 +1352,7 @@ qboolean PR_LoadProgs (const char *filename, qboolean fatal, unsigned int needcr
 
 	PR_SetEngineString("");
 	PR_EnableExtensions(qcvm->globaldefs);
+	PR_PatchRereleaseBuiltins();
 
 	return true;
 }
```
Of course, if the hardcoded values are too obscure, another function could be added that would take a function pointer such as PF_centerprint and return the index of the first builtin mapped to it.

**Comment by sezero** [comment] 2021-10-17 17:15
OK, let's Andrie apply the patch and close this.

**Comment by sezero** [comment] 2021-10-20 11:56
I just pushed Andrei's patch for this.

**Closed as completed** 2021-10-20 11:55 UTC
Labels: bug
