### ISSUE TITLE
Soul of Evil bug

### ISSUE THREAD

**Issue by NineKain** [Novum/vkQuake#387] opened 2021-11-10 20:32 UTC
https://user-images.githubusercontent.com/72826232/141189043-347d0aba-5e02-4719-88a3-1a8abbe77533.mp4

**Comment by Novum** [comment] 2021-11-13 05:08
And this does happen in QuakeSpasm or not?

**Comment by bstordeur** [comment] 2021-11-13 08:41
I was curious and looked at this, I can't reproduce this in any latest versions of QS / vkQ / QSS.
For the record it's the start map of SoE, after the 5 minute long non-skipable introduction...

**Comment by andrei-drexler** [comment] 2021-11-13 13:37
Couldn't reproduce it either - tried r_simd 0/1, r_novis 0/1 (in [this](https://www.quaddicted.com/reviews/soe_full.html) version). Maybe there's a conflicting external vis file? Either that, or a corrupted pak would be my guess.

P.S. to save some time, here's a save file after the unskippable intro: [soestart.zip](https://github.com/Novum/vkQuake/files/7532151/soestart.zip)

**Comment by Novum** [comment] 2021-11-14 05:31
Alright, I'm closing this then.

**Closed by Novum** 2021-11-14 05:31 UTC
