### ISSUE TITLE
[AD] reloading save breaks player bullets

### ISSUE THREAD

**Issue by bk4928412** [Novum/vkQuake#734] opened 2024-09-20 04:43 UTC
**Describe the bug**

on AD mod, reloading saves somehow causes weird lag and player's bullets stuck in mid air for a second. it gets worse with every reload. im not quite sure but it seems it only affects player bullets, i am unable to deal damage. at first, i thought maybe it was just qc related but then tried with ironwail, it doesnt have this issue.

**To Reproduce**

simply reload a save and try shooting an enemy.

**Expected behavior**

unable to deal damage, bullets wont fly

**Screenshots**

![vkquake0002](https://github.com/user-attachments/assets/42e64b72-8e10-44b1-ab49-bdb143b239ad)

**Desktop (please complete the following information):**

 - OS: [Windows]

**Mod**

AD 1.8

**Comment by vsonnier** [comment] 2024-09-20 14:32
I've seen similar things, but not on the few AD maps I played.... And in those cases reloading a save would make those 'stranded' items disappear. Moreover, those are more likely 'free' items, because if you do `r_showbboxes 1`, none of them have a box, which means they 'don't exist' anymore for the game, except for the renderer, as if there was a de-syncho between the two. 
Do you have `Fast loading = on` ? I've seen strange things with it on some maps only. Does switching it off improves the situation ?

Anyway, I need more info:
- version : ex `master`, or `1.31.1`, other ?
- Quake remaster or original one ?
- Does it work with a previous version like `131.0` ?
...etc.

**Comment by vsonnier** [comment] 2024-09-21 14:26
I can confirm that `Fast loading = on` is actually breaking some maps, and not only diplaying artifacts... 
For instance, in [Snack Map 3](https://www.slipseer.com/index.php?resources/snack-pack-3-trick-or-treat.280/) map `sm3_sze` (Overcast Citadel) you cannot access to the last area because the big lift never activates.

I'm now replaying all the pack with `Fast loading = off` and everything looks OK.

The fast loading feature was already present, but not exposed as a setting, in `1.30.1`. I don't know if it is fixable at all, I don't understand enough the way it works and have too little time to study it.

On the other hand, this feature is just too pratical for very big levels, (when it doesn't break things) I would like to keep it... Maybe as disabled, non-archived setting (`CVAR_NONE`), so it is always `off` at start, that way the player _have_ to activate it each time ?

**Comment by vsonnier** [comment] 2024-09-22 19:47
Thanks @j4reporting  for your tests... again ! The assertion error you encountered is actually __very__ interesting, and we may have a something of a lead this time. 

It is pure luck I added that assert in that code path, where `ED_Alloc` goes when it has to allocate a new edict, that is when it cannot re-use one on the free-list (for good reason) and actually raise the number of 'live' edicts. (num_edicts)
Now the code (dating from `1.30.0` no less) assumed it was _just_ new initialized memory (to 0), including `e->free = false (0)`.
Right ? Wrong ! The loading / fast-loading may change num_edicts a bit all the time, so there is no garantee that a new 'live' edict is properly reset, ...and we may even create one wrongly marked as free, like here.

I've made a branch (not published) bringing back the rebuilding of free-list (because we definitily cannot trust the current state of it after a load, fast or not), __AND__ a proper reset of the new edict in ED_Alloc... which coincidentally is exactly what `1.22.3` did, but it get dropped after that point (`1.22.3` pre-dates use of the original free-list as linked-list)

I'm now replaying Snack Pack 3 , Replicon, and soon Gibtropolis. I've also started Meat Jam and will test /re-test your particular save.

About the assert triggering or not, this is no mystery: on the Windows builds it is only enabled on Debug builds, as expected. I'm actually supprised it is present on Linux release builds, but hey !

**Comment by vsonnier** [comment] 2024-09-23 16:55
@bk4928412 
> present in what way, do you mean it fastloads maps automatically without any settings, or do you have to fastload manually

fastloading was, and is to be activated manually, but the mechanism is the same. Before `1.31.0` it was called `Game > Load last save = fast`  I simply separated it in a distinct option `Fast loading = on` but the process is the same.

**Comment by vsonnier** [comment] 2024-09-27 15:38
> Maybe it's a good idea to have a check for  !e->free and print something meaningful to console and inject a disconnect command?

No point now, at that particular place `ED_Alloc` new edicts are, by construction garanteed to be non-free. 

Our particular problem was litterally there since `1.22.3`, hidden first by the 'leak'-y management of edicts, fixed aftewards, and maginally hidden by the broken free-list implementation as a linked-list.

![Meme_Always_has_been](https://github.com/user-attachments/assets/065dd3c9-4561-4275-99ab-98e043060cab)

Played some maps now, no frozen (free) entities seen... Sometimes monsters get stuck in geometry, especially Fiends, but I've seen that before.

**Closed as completed by vsonnier** 2024-09-27 15:38 UTC
Labels: bug
