### ISSUE TITLE
Glitched models in certain mods

### ISSUE THREAD

**Issue by Quakefordays** [Novum/vkQuake#193] opened 2019-11-02 19:51 UTC
Hi, so occasionally in some of the mods I play with vkquake, a model or two for either an enemy or environmental detail will render in a very glitched manner.
![vkquake0001](https://user-images.githubusercontent.com/57300679/68076257-82d97f80-fd6f-11e9-995b-1005ae388b16.png)

**Comment by Novum** [comment] 2019-11-04 01:18
Not quite sure what you mean with glitched in that screenshot?

**Comment by Novum** [comment] 2019-11-04 01:18
If you mean the little texture squares, set the filter to "smooth" instead of "classic". This is by design.

**Comment by Novum** [comment] 2019-11-04 01:19
Oh you mean the sail, that's a duplicate of bug https://github.com/Novum/vkQuake/issues/191

**Closed by Novum** 2019-11-04 01:19 UTC

**Comment by Novum** [comment] 2019-11-09 19:18
https://github.com/Novum/vkQuake/releases/tag/1.03.0
