### ISSUE TITLE
Fullscreen mode - Shaking (Linux)

### ISSUE THREAD

**Issue by dmsun** [Novum/vkQuake#211] opened 2020-03-22 22:18 UTC
Hi,

when I enter into Fullscreen mode, the screen begins to shake (up and down) on a period of about 0.5s. Sound also clips are the screen does.

When I leave Fullscreen mode, the HUD is not fully viewable (health/armour is offscreen).

Resolution is 21:9
2560 by 1080p
V-Sync on/off does nothing
Vkquake v1.04.1

**Comment by Novum** [comment] 2020-03-23 00:04
Hardware and OS?

**Comment by dmsun** [comment] 2020-03-23 00:07
Arch Linux, kernel 5.5.10-arch1-1
Intel i7-3770
Nvidia gtx 960
Nvidia driver 440.64

Let me know if you need anything else.

**Comment by LethalManBoob** [comment] 2020-03-23 12:44
I would like to add to the discussion. Enabling exclusive fullscreen without r_desktopfullscreen makes the game run at 5fps.

**Comment by Novum** [comment] 2020-03-24 07:27
No idea, must be driver issues.

**Comment by dmsun** [comment] 2020-03-24 07:57
Could it be the resolution?

If I reduce resolution to 16:9, it plays fine.

**Comment by Novum** [comment] 2020-03-26 04:24
I can't test on Linux and I also don't have a 21:9 display. I have no idea.

**Comment by mg169706** [comment] 2020-04-13 15:29
I'm having the same issue. Running Ubuntu 19.04 with a Nvidia GTX 1070Ti using driver 440.59. I think the issue is related to the top nav bar. In Ubuntu at least, the vertical displacement seems identical to the vertical size of the nav bar. Perhaps there is some fight going on between the two?

**Comment by Elrondo46** [comment] 2020-05-01 07:04
Same here with Manjaro in Gnome, and reload infinite issue in fullscreen in vkquake2

**Comment by Rugaliz** [comment] 2020-05-01 09:50
Same issue with Fedora 32 and Gnome. It's probably the top bar interfering somehow.

**Comment by goodjaerb** [comment] 2020-05-03 23:55
Just encountered this issue on new ubuntu 20.04. I made a video to show what it is doing. It almost seems similar to a vkQuake2 issue https://github.com/kondrak/vkQuake2/issues/95 but also quite different. I believe he has resolved his issue, I still have to comment to him about it.

I attached the output from the terminal. It's like it's resetting the video over and over which is similar to vkQuake2's issue I described.

https://www.youtube.com/watch?v=btpHfEzCQhY 

[vkquake_log.txt](https://github.com/Novum/vkQuake/files/4572297/vkquake_log.txt)

**Comment by Elrondo46** [comment] 2020-05-08 07:44
the issue was reported by me in vkQuake 2 for infinite reload bug and solved for vkQuake2.

vkQuake have a similar bug but not same reaction: shaking

**Comment by mg169706** [comment] 2020-05-08 08:47
> 
> 
> the issue was reported by me in vkQuake 2 for infinite reload bug and solved for vkQuake2.
> 
> vkQuake have a similar bug but not same reaction: shaking

When did you report the bug roughly? I'll take a look in the commit tree and see if I can apply a similar fix here. No promises mind you...

**Comment by kondrak** [comment] 2020-05-08 08:55
The fix in vkQuake2 was not to recreate entire window during Vulkan restart, the latter was causing `VK_ERROR_OUT_OF_DATE_KHR` to be thrown constantly which resulted in the window being rebuilt perpetually. Note: vkQuake2 is not using SDL2.
Looking at the logs from @goodjaerb it seems this could be a similar case. @mg169706 if you can repro this, I'd check if by any chance `SDL_SetWindowSize` is causing this, can't think of anything else at this point without being able to check it myself.

**Comment by mg169706** [comment] 2020-05-08 10:41
Log file attached.
[log.txt](https://github.com/Novum/vkQuake/files/4598485/log.txt)

**Comment by kondrak** [comment] 2020-05-08 11:11
Can't see anything more than what @goodjaerb posted in his log, I'd try a similar approach to mine and just recreate Vulkan without touching any window related SDL functions if OUT_OF_DATE/other errors occur since I think this is what could be causing this problem, at least speaking from experiences with vkQuake2.

**Comment by kondrak** [comment] 2020-05-08 11:16
Fixing issues like these is pretty furstrating btw, since it's impossible to repro it on every driver. I talked to Khronos recently and will be submitting a proposal on some emulation layer that could possibly facilitate work like this in the future.

**Comment by mg169706** [comment] 2020-05-08 11:41
I've started trying to trace the source by adding in some debug telemetry, tracking when the vid_changed flag is raised... 
[log.txt](https://github.com/Novum/vkQuake/files/4598716/log.txt)

**Comment by kondrak** [comment] 2020-05-08 12:01
Yup, behavior looks about right. Still suspecting `SDL_SetWindowSize` or any other SDL functions that modifies the window/surface/whatever during renderer recreation.

**Comment by Novum** [comment] 2020-05-09 15:43
I believe this is an SDL2 bug, therefore I'm going to close this. Please report it on their bug tracker.

**Closed by Novum** 2020-05-09 15:43 UTC

**Comment by Rugaliz** [comment] 2020-05-16 12:07
Before I had a NVIDIA GPU, now I  switched to an AMD GPU using kernel drivers in Linux and this issue went away...could this a SDL issue with Nvidia drivers?
