### ISSUE TITLE
Scaled Window mode

### ISSUE THREAD

**Issue by smgorden** [Novum/vkQuake#219] opened 2020-05-02 10:58 UTC
Feature Request: Scaled windowed (non-fullscreen) mode for playing at low resolutions in a client window scaled to 2x, 3x, etc integer values.

**Comment by Novum** [comment] 2021-01-03 02:25
Duplicate of https://github.com/Novum/vkQuake/issues/229

**Closed by Novum** 2021-01-03 02:25 UTC
Labels: enhancement
