### ISSUE TITLE
Arcane Dimensions 1.8 (Patch 1) crash after death

### ISSUE THREAD

**Issue by Berzerk2k2** [Novum/vkQuake#249] opened 2020-10-18 15:32 UTC
The new 1.8 (+ Patch 1) version of **Arcane Dimensions** keeps crashing when you die. The error message says **"Could not allocate memory for texture"**. I tested this in the new map **"Tears Of The False God"**.

![ad18p1errorvkquake](https://user-images.githubusercontent.com/60928292/96372701-65f8b080-1168-11eb-9133-29b51bc631a4.png)

**Comment by JuanchoES** [comment] 2020-10-18 16:30
i 100% this map yesterday without problems, you need the latest vkquake version.

https://drive.google.com/file/d/1YFOzgz7JmQ_941iwB7GzohZxcuBjIDDs/view?usp=sharing


![image](https://user-images.githubusercontent.com/70743149/96373906-b0c9f680-116f-11eb-950c-f667d9acab56.png)

**Comment by Berzerk2k2** [comment] 2020-10-18 17:58
I used the latest official version **1.04.1** and with that every time I died AD would crash with the error message mentioned in my previous post. Will try the one from that Google Drive link later.

**Comment by JuanchoES** [comment] 2020-10-18 18:50
> I used the latest official version **1.04.1** and with that every time I died AD would crash with the error message mentioned in my previous post.

yea, i know that the 1.04.1 version crashes, but YOU need to compile the newest vkquake version, the version that you have is old. i uploaded the newest versios of vkquake in my google drive https://drive.google.com/file/d/1YFOzgz7JmQ_941iwB7GzohZxcuBjIDDs/view?usp=sharing
If you use this version the map is not gonna crash.

**Comment by Berzerk2k2** [comment] 2020-10-18 19:32
That Google link looks like anything except a new **official** vkQuake release. I'll wait until 1.40.2 or whatever it'll be named has been released by Novum.

**Comment by bstordeur** [comment] 2020-10-18 20:09
Yeah getting a new official release with the newest codebase that seems to include a fix for this would be great!

**Comment by AnotherLife** [comment] 2020-10-18 20:48
> That Google link looks like anything except a new **official** vkQuake release. I'll wait until 1.40.2 or whatever it'll be named has been released by Novum.

That link is to a private build of vkQuake. I took the dll files and the winquake.exe and replaced the files in my vkQuake folder. (I renamed winquake.exe to vkQuake.exe)

**Comment by JuanchoES** [comment] 2020-10-18 22:10
> That Google link looks like anything except a new **official** vkQuake release. I'll wait until 1.40.2 or whatever it'll be named has been released by Novum.

![image](https://user-images.githubusercontent.com/70743149/96386998-71b39980-119f-11eb-8efe-6ec663e90629.png)

**Comment by vsonnier** [comment] 2020-10-19 04:51
> Yeah getting a new official release with the newest codebase that seems to include a fix for this would be great!

Yes indeed, @bstordeur that would be great. What would be **really** awesome is seing the `qss-branch` work completed. :) 

For now Tears Of The False God runs great with the `master` version, but I wouldn't mind seeing the QuakeSpasm-Spiked bells and whistles for AD levels in vkQuake 👍

**Comment by Berzerk2k2** [comment] 2020-10-19 17:39
> ![image](https://user-images.githubusercontent.com/70743149/96386998-71b39980-119f-11eb-8efe-6ec663e90629.png)

Hey no offense. I appreciate that you wanted to help. It's just that I'm very very cautious when it comes to custom/unofficial versions since I had problems with such things in the past.

**Comment by JuanchoES** [comment] 2020-10-19 19:54
> > ![image](https://user-images.githubusercontent.com/70743149/96386998-71b39980-119f-11eb-8efe-6ec663e90629.png)
> 
> Hey no offense. I appreciate that you wanted to help. It's just that I'm very very cautious when it comes to custom/unofficial versions since I had problems with such things in the past.

Bro, the link that i send you is a version of vkquake with the latest OFFICIAL commits made by novum THE DEVELOPER.

I just compiled the new O F F I C I A L code and made a usable vkquake folder with the exe and the DLLs, this is official i didnt make a custom/unofficial version.

**Comment by micwoj92** [comment] 2020-10-19 19:57
> > > ![image](https://user-images.githubusercontent.com/70743149/96386998-71b39980-119f-11eb-8efe-6ec663e90629.png)
> > 
> > 
> > Hey no offense. I appreciate that you wanted to help. It's just that I'm very very cautious when it comes to custom/unofficial versions since I had problems with such things in the past.
> 
> Bro, the link that i send you is a version of vkquake with the latest OFFICIAL commits made by novum THE DEVELOPER.
> 
> I just compiled the new O F F I C I A L code and made a usable vkquake folder with the exe and the DLLs, this is official i didnt make a custom/unofficial version.

This is unofficial vkQuake version because the binaries was not released by Novum. Why do you even argue?

**Comment by mjr4077au** [comment] 2020-10-19 20:07
> > > Hey no offense. I appreciate that you wanted to help. It's just that I'm very very cautious when it comes to custom/unofficial versions since I had problems with such things in the past.
> > 
> > 
> > Bro, the link that i send you is a version of vkquake with the latest OFFICIAL commits made by novum THE DEVELOPER.
> > I just compiled the new O F F I C I A L code and made a usable vkquake folder with the exe and the DLLs, this is official i didnt make a custom/unofficial version.
> 
> This is unofficial vkQuake version because the binaries were not released by Novum. Why do you even argue?

The reason is that they went out of their way to help someone who wanted an updated version and got rejected in a very rude way. Time was taken to build, upload and share the binary. The other problem is this issue is now getting clogged up with bullshit and I keep getting emails about it all the time when the issue should actually just be closed since the issue is fixed in master.

**Comment by JuanchoES** [comment] 2020-10-19 20:10
> > > Hey no offense. I appreciate that you wanted to help. It's just that I'm very very cautious when it comes to custom/unofficial versions since I had problems with such things in the past.
> > 
> > 
> > Bro, the link that i send you is a version of vkquake with the latest OFFICIAL commits made by novum THE DEVELOPER.
> > I just compiled the new O F F I C I A L code and made a usable vkquake folder with the exe and the DLLs, this is official i didnt make a custom/unofficial version.
> 
> This is unofficial vkQuake version because the binaries were not released by Novum. Why do you even argue?

Mmmm... I compiled that version with the official code, the fix that the OP needed was 2bcd4ef (included in the version that i send) made by Axel Gneiting, the developer...

**Comment by micwoj92** [comment] 2020-10-19 20:22
> > > Bro, the link that i send you is a version of vkquake with the latest OFFICIAL commits made by novum THE DEVELOPER.
> > > I just compiled the new O F F I C I A L code and made a usable vkquake folder with the exe and the DLLs, this is official i didnt make a custom/unofficial version.
> > 
> > 
> > This is unofficial vkQuake version because the binaries were not released by Novum. Why do you even argue?
> 
> Mmmm... I compiled that version with the official code, the fix that the OP needed was [2bcd4ef](https://github.com/Novum/vkQuake/commit/2bcd4ef65abc44684ff6a49ed531f877c300c87c) (included in the version that i send) made by Axel Gneiting, the developer...
No doubt that that code was written by Axel Gneiting. No doubt that it includes fix. I fully understand what you did and I even ran that binary by myself, but do you know what **official** means?
![image](https://user-images.githubusercontent.com/45581170/96506767-7d16cb80-1258-11eb-847d-8aa29dede936.png)
Here, this is last **official** version released by Novum. All commits after that tag do not belong to any official vkQuake release. It is up to Berzerk2k2 if he trusts you and wants to run your binary or not.

**Comment by mjr4077au** [comment] 2020-10-19 20:32
He still could have said no in a better way.

Perhaps consideration for some kind of Continuous Integration should be done? I work on Raze and with our CI setup, artifacts are left behind from the build process that can be downloaded: https://github.com/coelckers/Raze/runs/1274386868. Quick way to get a development build 👍.

**Comment by mgtroyas** [comment] 2020-10-20 18:36
This more recent version also fixed my problem with "Tears Of The False God", thank you very much!

I'd suggest doing an official release so all the people that use vkQuake and is playing now AD 1.8 doesn't get frustrated. I just saw this thread because I was going to open a new issue.

**Comment by Novum** [comment] 2020-10-26 20:50
I deleted the off topic crap in here. Behave.

**Comment by mjr4077au** [comment] 2020-10-26 21:17
Any thoughts on a Continuous Integration setup though? Tests your code cross-platform if set up to do so and most leave artifacts available for download, so people who can't/won't do compiles can test out pre-release stuff. Might also help make releases more robust if testing can be done prior to a release.

**Comment by Novum** [comment] 2020-10-27 01:16
Complete overkill for something like this.

**Comment by aboutafter** [comment] 2020-10-27 11:03
> This is indeed a good reason to make a new release, but I want to test it first.

I know this is not a suggestions thread, but since you are planning on patching vkQuake for AD1.8, do you think you could add the ability to use the new HUDs too?

Thank you very much for your work.

**Comment by Novum** [comment] 2020-10-29 22:13
I believe this could be partially ADs fault. There seems to be a mesh leak but only in the ad_tears map.

**Comment by Novum** [comment] 2020-10-29 22:19
Yeah, it's somehow reloading all the models every time ad_tears is loaded up. This is coming from some QC code. I'll modify my code it so it may leak until VRAM is exhausted, but this is really something that needs to be patched in the map code as well.

**Comment by Novum** [comment] 2020-10-29 22:21
"Fixed" with cb02137

**Comment by Novum** [comment] 2020-10-30 00:55
@bstordeur I checked QuakeSpasm and the same thing is happening. Loads all the alias models every time ad_tears is loaded. Same leak.

**Closed** 2020-10-30 00:59 UTC

**Comment by bstordeur** [comment] 2020-10-30 08:43
Thanks for the release @Novum !
Is this leak happening only on AD? Or can you observe it happening on others mods or id1 as well? There shouldn't be anything specific for ad_tears anyways, I'll ask Sock if that sounds like something different going on in the AD QC.

**Comment by Novum** [comment] 2020-10-30 10:40
It only happens with this map.
