### ISSUE TITLE
Crash when using PNG as texture for a md5 model

### ISSUE THREAD

**Issue by NurglesHogweed** [Novum/vkQuake#752] opened 2024-11-26 18:59 UTC
Engine version: "master" from november 12, for Linux.
Error text:
```
vkquake: ../Quake/gl_texmgr.c:694: TexMgr_Downsample: Assertion `(out_width >= 1) && (out_width < in_width)' failed.
```
The texture I tried to use is 256x256. FTEQW, QSS and fimg have no problems with it.

**Comment by vsonnier** [comment] 2024-11-26 19:35
Hello @NurglesHogweed, please provide the necessary files and procedure to reproduce this use case.

**Comment by NurglesHogweed** [comment] 2024-11-26 20:19
You can extract, for example, pak0.pak\progs\v_shot_00_00.lmp, convert it to PNG, put it to id1\progs and see what happens.

**Comment by vsonnier** [comment] 2024-11-27 05:59
Thanks, that was useful. Turns out the texture support in MD5 was not properly ported from QSS, only `.lmp` worked. This is now fixed I think. I've tried with both 8bit and 24bit `.png` and also `.pcx` and it seems to work.

**Closed by vsonnier** 2024-11-27 05:59 UTC
Labels: bug
