### ISSUE TITLE
[Bug] Sounds don't work when using the 2021 remaster PAKs

### ISSUE THREAD

**Issue by Emalcat** [Novum/vkQuake#421] opened 2022-01-16 10:28 UTC
# System info:
OS: Windows 10 Home version 19042.1466
GPU: AMD Vega 3 Graphics
CPU: AMD Ryzen 3 3250U
vkquake version - 1.12.2

# Bug:
When I try to use the new quake .PAK files, while music works flawlessly, sounds don't appear audible and the console is full of error like the pic below
# Reproduction:
Open id1 from the quake 2021 remaster, or try to jump
![quake error](https://user-images.githubusercontent.com/88663610/149656259-b28387c3-44a0-4568-bfca-97cd5d325b72.PNG)

**Comment by Novum** [comment] 2022-01-17 21:49
No idea. I suspect they updated the game again and broke vkQuake.

**Comment by Novum** [comment] 2022-01-17 21:51
Cannot reproduce this with latest Steam version of the re-release. If you can't provide more details I will close this soon.

**Closed** 2022-01-17 21:56 UTC
