### ISSUE TITLE
SZ_GetSpace overflow  in AD1.7 ad_sepulcher  and sv_protocoll FTE999

### ISSUE THREAD

**Issue by j4reporting** [Novum/vkQuake#484] opened 2022-06-06 15:59 UTC
accidentally encountered this error when I started the previous version of Arcane Dimensions  

vkquake: current git master version
game: ad 1.7/1.7p1  
map ad_sepulcher

```
]map ad_sepulcher
vkQuake 1.13.1 Server (4539 CRC)
The Forgotten Sepulcher
Using protocol fte999
Allocating lightmap compute surface data (12390 KB)
SZ_GetSpace: overflow

```

map  starts  with sv_protocoll fte666
```
]sv_protocol fte666
changes will not take effect until the next level load.
]map ad_sepulcher

vkQuake 1.13.1 Server (4539 CRC)

The Forgotten Sepulcher
Using protocol fte666
Allocating lightmap compute surface data (12390 KB)
Slipgate_Touris entered the game
         Arcane Dimensions v1.70 Patch 1
```

map starts  in QSS version  2021-10-14   and sv_protocoll fte999

**Comment by temx** [comment] 2022-06-06 19:20
This is caused by the faster loading :( It's mutually exclusive with #470 too.
Set `host_maxfps` to `10` during load, or use the latest mod version.
We can't really increase that buffer past 64K.

**Comment by Novum** [comment] 2022-06-06 22:05
Because this is a mod issue and has been fixed already in their code I will close this.

**Closed by Novum** 2022-06-06 22:05 UTC

**Comment by j4reporting** [comment] 2022-06-06 23:02
I had found the `sv_gameplayfix_spawnbeforethinks` setting in the AD1.7 readme as well, and when testing with QSS it was disabled.
 
Does this mean that faster loading only occurs in network isolation mode?  
I can load the map with host_maxfps 72. With 73 it fails, and that since version 1.12.1

**Comment by temx** [comment] 2022-06-06 23:08
No, but network isolation affects how often the server runs in relation to the client, as well as how much the server time can advance per "client" (render) frame. During loading there are long frames, so these effects are amplified.
